### ISSUE TITLE
Error Loading Model in predict_ss_rna.py Due to CUDA Device Mismatch

### ISSUE THREAD

**Issue by nicoaira** [Bruce-ywj/ERNIE-RNA#8]
While running the predict_ss_rna.py script from the ERNIE-RNA repository, I encountered the following error:

`python predict_ss_rna.py  --seqs_path='./data/test_seqs.fasta' --device=0
`

(note that I changed device='cuda:0' to device=0 because it was expecting an integer

```
Traceback (most recent call last):
  File "/home/nicolas/programs/ERNIE-RNA/predict_ss_rna.py", line 235, in <module>
    pres_ss = predict(seqs_lst, args.ss_rna_checkpoint, args.ernie_rna_pretrained_checkpoint, args.arg_overrides, args.device)
  File "/home/nicolas/programs/ERNIE-RNA/predict_ss_rna.py", line 177, in predict
    state_dict = torch.load(best_model_path)
  File "/home/nicolas/miniforge3/envs/ERNIE-RNA/lib/python3.9/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/nicolas/miniforge3/envs/ERNIE-RNA/lib/python3.9/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/nicolas/miniforge3/envs/ERNIE-RNA/lib/python3.9/site-packages/torch/serialization.py", line 857, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/nicolas/miniforge3/envs/ERNIE-RNA/lib/python3.9/site-packages/torch/serialization.py", line 846, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "/home/nicolas/miniforge3/envs/ERNIE-RNA/lib/python3.9/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/nicolas/miniforge3/envs/ERNIE-RNA/lib/python3.9/site-packages/torch/serialization.py", line 151, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/nicolas/miniforge3/envs/ERNIE-RNA/lib/python3.9/site-packages/torch/serialization.py", line 142, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on CUDA device '
RuntimeError: Attempting to deserialize object on CUDA device 7 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.
```

**System Information:**

- OS: Ubuntu 22.04.3 LTS
- Kernel Version: 6.8.0-48-generic
- Architecture: x86_64
- CUDA Driver Version: 12.2
- GPU: NVIDIA GeForce RTX 3070 Mobile / Max-Q
- NVIDIA Driver Version: 535.183.01

The error suggests that the model was saved on a system with multiple GPUs (specifically, device 7), but my current system has only one GPU (device 0). This discrepancy causes the deserialization process to fail.

**Suggested Solution:**
To resolve this, modify the `predict_ss_rna.py` script to map the loaded model to the available device. Locate the line where the model is loaded:

```
state_dict = torch.load(best_model_path)
```
and change it to:

```
state_dict = torch.load(best_model_path, map_location=f'cuda:{device}')
```

**Comment by Shuo-Zhan** [comment]
Thank you very much for your questions and suggestions! We will quickly verify this issue. If the issue exists, we will submit the new version of the Python file to GitHub.
